is_augmentation: true  # Changed from 'augmentation' to match the code
image_size:
  - 224
  - 224
  - 3
batch_size: 16
epochs: 1
learning_rate: 0.01
# ... rest of your file
weights: imagenet
include_top: false
classes: 4
freeze_all: true
freeze_till: null